name = "Create 3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5dee199be5564b9c477ba228bb94fd9e3b63e3a782e54564ba10f062c0bc17c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
