name = "Create 3"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdb4dee6423e6b583b3d57d7567de289c2c50166e636ea80788eadabf92d38e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
